In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import sys
sys.path.insert(0, '../../src/')
import data_loader
pd.set_option('display.max_columns', None)

In [2]:
player_info = pd.read_csv("/home/matej/Documents/Projects/nba-data-mining/data/raw/player-data/player_info.csv")
lineups = pd.read_csv("/home/matej/Documents/Projects/nba-data-mining/data/processed/lineups-all-seasons.csv")

In [6]:
seasons = data_loader.load_data()

In [ ]:
def extract_games_started():
    player_info["games_started"] = player_info.apply(lambda x:
                                (lineups[(lineups["season"] == x["Season"]) & ((lineups["home_player1_id"] == x["Player ID"]) | (lineups["home_player2_id"] == x["Player ID"]) | (lineups["home_player3_id"] == x["Player ID"]) | (lineups["home_player4_id"] == x["Player ID"]) | (lineups["home_player5_id"] == x["Player ID"]) |
                                (lineups["visitor_player1_id"] == x["Player ID"]) | (lineups["visitor_player2_id"] == x["Player ID"]) | (lineups["visitor_player3_id"] == x["Player ID"]) | (lineups["visitor_player4_id"] == x["Player ID"]) | (lineups["visitor_player5_id"] == x["Player ID"]))]["game_id"].count()), axis=1)

In [62]:
def extract_games_played():
    games_played = []

    for year in range(0, 19):
    #for year in range(0, 19):

        file_str = ""

        if year < 9:
            file_str = "200{}-0{}".format(year, year + 1)
        elif year == 9:
            file_str = "200{}-{}".format(year, year + 1)
        else:
            file_str = "20{}-{}".format(year, year + 1)

        season_data = data_loader.load_data(seasons=[file_str])

        tmp = player_info[player_info["Season"] == file_str].apply(lambda x: season_data[((season_data["PLAYER1_ID"] == str(x["Player ID"])) | (season_data["PLAYER2_ID"] == str(x["Player ID"])) | (season_data["PLAYER3_ID"] == str(x["Player ID"])))]["GAME_ID"].nunique(), axis = 1)
        games_played.extend(tmp)
        
        print("{} ... done".format(file_str))

2000-01 ... done
2001-02 ... done
2002-03 ... done
2003-04 ... done
2004-05 ... done
2005-06 ... done
2006-07 ... done
2007-08 ... done
2008-09 ... done
2009-10 ... done
2010-11 ... done
2011-12 ... done
2012-13 ... done
2013-14 ... done
2014-15 ... done
2015-16 ... done
2016-17 ... done
2017-18 ... done
2018-19 ... done

In [77]:
player_info

,Player,Team,Age,Height,Weight,College,Country,Draft Year,Draft Round,Draft Number,GP,PTS,REB,AST,NetRtg,OREB%,DREB%,USG%,TS%,AST%,Player ID,Season,games_started,games_played
0,A.C. Green,MIA,37,6-9,225,Oregon State,USA,1985,1,23,82,367,313,39,3.8,7.6%,15.1%,13.7%,49.2%,5.0%,920,2000-01,2,82.0
1,A.J. Guyton,CHI,23,6-1,180,Indiana,USA,2000,2,32,33,198,36,64,-11.0,1.6%,4.6%,16.7%,49.5%,19.8%,2062,2000-01,9,33.0
2,Aaron McKie,PHI,28,6-5,209,Temple,USA,1994,1,17,76,878,311,377,7.3,1.5%,11.5%,18.6%,54.9%,26.4%,243,2000-01,35,76.0
3,Aaron Williams,NJN,29,6-9,225,Xavier,USA,Undrafted,Undrafted,Undrafted,82,838,590,88,-7.9,8.9%,17.6%,17.7%,53.3%,6.8%,1425,2000-01,25,82.0
4,Adam Keefe,GSW,31,6-9,230,Stanford,USA,1992,1,10,67,168,209,36,-10.1,9.5%,15.0%,11.3%,45.0%,6.6%,228,2000-01,15,67.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9398,Zach LaVine,CHI,25,6-6,200,UCLA,USA,2014,1,13,60,1530,289,254,-4.4,1.9%,12.5%,31.2%,56.8%,21.8%,203897,2019-20,0,NaN
9399,Zach Norvell Jr.,GSW,22,6-5,205,Gonzaga,USA,2019,NaN,NaN,5,10,6,3,-32.3,0.0%,20.7%,14.7%,40.2%,9.1%,1629668,2019-20,0,NaN
9400,Zhaire Smith,PHI,21,6-3,205,Texas Tech,USA,2018,1,16,7,8,2,2,-12.3,0.0%,8.0%,16.5%,31.3%,8.3%,1629015,2019-20,0,NaN
9401,Zion Williamson,NOP,19,6-6,284,Duke,USA,2019,1,1,24,540,150,50,5.1,9.2%,11.4%,29.1%,61.6%,11.9%,1629627,2019-20,0,NaN
9402,Zylan Cheatham,NOP,24,6-5,220,Arizona State,USA,Undrafted,Undrafted,Undrafted,4,12,9,3,-23.9,6.2%,12.8%,10.3%,66.7%,9.4%,1629597,2019-20,0,NaN

In [4]:
# for testing
id = 2544

lineups[(lineups["season"] == "2011-12") & ((lineups["home_player1_id"] == id) | (lineups["home_player2_id"] == id) | (lineups["home_player3_id"] == id) | (lineups["home_player4_id"] == id) | (lineups["home_player5_id"] == id) |
        (lineups["visitor_player1_id"] == id) | (lineups["visitor_player2_id"] == id) | (lineups["visitor_player3_id"] == id) | (lineups["visitor_player4_id"] == id) | (lineups["visitor_player5_id"] == id))]["game_id"].count()

51