In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import sys
sys.path.insert(0, '../../src/')
import data_loader
pd.set_option('display.max_columns', None)

In [2]:
player_info = pd.read_csv("/home/matej/Documents/Projects/nba-data-mining/data/raw/player-data/player_info.csv")
lineups = pd.read_csv("/home/matej/Documents/Projects/nba-data-mining/data/processed/lineups-all-seasons.csv")

In [6]:
seasons = data_loader.load_data()

In [11]:
seasons.head()

,Unnamed: 0,EVENTMSGACTIONTYPE,EVENTMSGTYPE,EVENTNUM,GAME_ID,HOMEDESCRIPTION,PCTIMESTRING,PERIOD,PERSON1TYPE,PERSON2TYPE,PERSON3TYPE,PLAYER1_ID,PLAYER1_NAME,PLAYER1_TEAM_ABBREVIATION,PLAYER1_TEAM_CITY,PLAYER1_TEAM_ID,PLAYER1_TEAM_NICKNAME,PLAYER2_ID,PLAYER2_NAME,PLAYER2_TEAM_ABBREVIATION,PLAYER2_TEAM_CITY,PLAYER2_TEAM_ID,PLAYER2_TEAM_NICKNAME,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ABBREVIATION,PLAYER3_TEAM_CITY,PLAYER3_TEAM_ID,PLAYER3_TEAM_NICKNAME,SCORE,SCOREMARGIN,VISITORDESCRIPTION,WCTIMESTRING,season_name,home_shot_distance,visitor_shot_distance
0,0,0,PERIOD_BEGIN,0,20001116,NaN,12:00,1,0.0,0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12:11 PM,2000-01,NaN,NaN
1,1,0,JUMP_BALL,1,20001116,Jump Ball Grant vs. Mutombo: Tip to Hill,12:00,1,HOME_PLAYER,VISITOR_PLAYER,VISITOR_PLAYER,258,Brian Grant,MIA,Miami,1610612748.0,Heat,87,Dikembe Mutombo,PHI,Philadelphia,1610612755.0,76ers,238,Tyrone Hill,PHI,Philadelphia,1610612755.0,76ers,NaN,NaN,NaN,12:12 PM,2000-01,NaN,NaN
2,2,Jump Shot,FIELD_GOAL_MADE,2,20001116,NaN,11:45,1,VISITOR_PLAYER,0,0,947,Allen Iverson,PHI,Philadelphia,1610612755.0,76ers,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,2 - 0,-2,Iverson 21' Jump Shot (2 PTS),12:13 PM,2000-01,NaN,21.0
3,3,1,FOUL,3,20001116,NaN,11:28,1,VISITOR_PLAYER,0,TIMEOUT,238,Tyrone Hill,PHI,Philadelphia,1610612755.0,76ers,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hill P.FOUL (P1.T1),12:13 PM,2000-01,NaN,NaN
4,4,Jump Shot,FIELD_GOAL_MADE,4,20001116,Mason 17' Jump Shot (2 PTS),11:19,1,HOME_PLAYER,0,0,193,Anthony Mason,MIA,Miami,1610612748.0,Heat,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,2 - 2,TIE,NaN,12:13 PM,2000-01,17.0,NaN

In [39]:
player_info[player_info["Season"] == "2000-01"]

,Unnamed: 0,Unnamed: 0.1,Player,Team,Age,Height,Weight,College,Country,Draft Year,Draft Round,Draft Number,GP,PTS,REB,AST,NetRtg,OREB%,DREB%,USG%,TS%,AST%,Player ID,Season,games_started
0,0,0,A.C. Green,MIA,37,6-9,225,Oregon State,USA,1985,1,23,82,367,313,39,3.8,7.6%,15.1%,13.7%,49.2%,5.0%,920,2000-01,2
1,1,1,A.J. Guyton,CHI,23,6-1,180,Indiana,USA,2000,2,32,33,198,36,64,-11.0,1.6%,4.6%,16.7%,49.5%,19.8%,2062,2000-01,9
2,2,2,Aaron McKie,PHI,28,6-5,209,Temple,USA,1994,1,17,76,878,311,377,7.3,1.5%,11.5%,18.6%,54.9%,26.4%,243,2000-01,35
3,3,3,Aaron Williams,NJN,29,6-9,225,Xavier,USA,Undrafted,Undrafted,Undrafted,82,838,590,88,-7.9,8.9%,17.6%,17.7%,53.3%,6.8%,1425,2000-01,25
4,4,4,Adam Keefe,GSW,31,6-9,230,Stanford,USA,1992,1,10,67,168,209,36,-10.1,9.5%,15.0%,11.3%,45.0%,6.6%,228,2000-01,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
436,436,436,Will Perdue,POR,35,7-0,240,Vanderbilt,USA,1988,1,11,13,14,18,2,1.6,11.3%,24.5%,8.0%,65.1%,5.3%,781,2000-01,1
437,437,437,William Avery,MIN,21,6-2,197,Duke,USA,1999,1,14,55,154,29,75,-4.5,1.1%,5.1%,19.2%,48.2%,28.6%,1895,2000-01,2
438,438,438,Zan Tabak,IND,31,7-0,257,None,Croatia,1991,2,51,55,216,213,33,0.3,9.2%,18.4%,15.7%,52.3%,7.0%,440,2000-01,15
439,439,439,Zendon Hamilton,LAC,26,6-11,254,St. John's,USA,Undrafted,Undrafted,Undrafted,3,9,8,0,-20.6,13.0%,26.3%,30.6%,35.9%,0.0%,1985,2000-01,0
440,440,440,Zydrunas Ilgauskas,CLE,26,7-3,260,None,Lithuania,1996,1,20,24,281,160,18,-0.7,11.3%,15.1%,24.3%,52.4%,5.7%,980,2000-01,23

In [62]:
def extract_games_played():
    games_played = []

    for year in range(0, 19):
    #for year in range(0, 19):

        file_str = ""

        if year < 9:
            file_str = "200{}-0{}".format(year, year + 1)
        elif year == 9:
            file_str = "200{}-{}".format(year, year + 1)
        else:
            file_str = "20{}-{}".format(year, year + 1)

        season_data = data_loader.load_data(seasons=[file_str])

        tmp = player_info[player_info["Season"] == file_str].apply(lambda x: season_data[((season_data["PLAYER1_ID"] == str(x["Player ID"])) | (season_data["PLAYER2_ID"] == str(x["Player ID"])) | (season_data["PLAYER3_ID"] == str(x["Player ID"])))]["GAME_ID"].nunique(), axis = 1)
        games_played.extend(tmp)
        
        print("{} ... done".format(file_str))

2000-01 ... done
2001-02 ... done
2002-03 ... done
2003-04 ... done
2004-05 ... done
2005-06 ... done
2006-07 ... done
2007-08 ... done
2008-09 ... done
2009-10 ... done
2010-11 ... done
2011-12 ... done
2012-13 ... done
2013-14 ... done
2014-15 ... done
2015-16 ... done
2016-17 ... done
2017-18 ... done
2018-19 ... done

In [60]:
player_info

,Unnamed: 0,Unnamed: 0.1,Player,Team,Age,Height,Weight,College,Country,Draft Year,Draft Round,Draft Number,GP,PTS,REB,AST,NetRtg,OREB%,DREB%,USG%,TS%,AST%,Player ID,Season,games_started,games_played
0,0,0,A.C. Green,MIA,37,6-9,225,Oregon State,USA,1985,1,23,82,367,313,39,3.8,7.6%,15.1%,13.7%,49.2%,5.0%,920,2000-01,2,NaN
1,1,1,A.J. Guyton,CHI,23,6-1,180,Indiana,USA,2000,2,32,33,198,36,64,-11.0,1.6%,4.6%,16.7%,49.5%,19.8%,2062,2000-01,9,NaN
2,2,2,Aaron McKie,PHI,28,6-5,209,Temple,USA,1994,1,17,76,878,311,377,7.3,1.5%,11.5%,18.6%,54.9%,26.4%,243,2000-01,35,NaN
3,3,3,Aaron Williams,NJN,29,6-9,225,Xavier,USA,Undrafted,Undrafted,Undrafted,82,838,590,88,-7.9,8.9%,17.6%,17.7%,53.3%,6.8%,1425,2000-01,25,NaN
4,4,4,Adam Keefe,GSW,31,6-9,230,Stanford,USA,1992,1,10,67,168,209,36,-10.1,9.5%,15.0%,11.3%,45.0%,6.6%,228,2000-01,15,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9398,9398,9398,Zach LaVine,CHI,25,6-6,200,UCLA,USA,2014,1,13,60,1530,289,254,-4.4,1.9%,12.5%,31.2%,56.8%,21.8%,203897,2019-20,0,NaN
9399,9399,9399,Zach Norvell Jr.,GSW,22,6-5,205,Gonzaga,USA,2019,NaN,NaN,5,10,6,3,-32.3,0.0%,20.7%,14.7%,40.2%,9.1%,1629668,2019-20,0,NaN
9400,9400,9400,Zhaire Smith,PHI,21,6-3,205,Texas Tech,USA,2018,1,16,7,8,2,2,-12.3,0.0%,8.0%,16.5%,31.3%,8.3%,1629015,2019-20,0,NaN
9401,9401,9401,Zion Williamson,NOP,19,6-6,284,Duke,USA,2019,1,1,24,540,150,50,5.1,9.2%,11.4%,29.1%,61.6%,11.9%,1629627,2019-20,0,NaN
9402,9402,9402,Zylan Cheatham,NOP,24,6-5,220,Arizona State,USA,Undrafted,Undrafted,Undrafted,4,12,9,3,-23.9,6.2%,12.8%,10.3%,66.7%,9.4%,1629597,2019-20,0,NaN

In [21]:
seasons[(seasons["season_name"] == "2010-11") & ((seasons["PLAYER1_ID"] == "201188") | (seasons["PLAYER2_ID"] == "201188") | (seasons["PLAYER3_ID"] == "201188"))]["GAME_ID"].nunique()

# seasons[(seasons["season_name"] == "2010-11") & (seasons["PLAYER1_ID"] == "201188")]

81

In [8]:
player_info["games_started"] = player_info.apply(lambda x:
                                (lineups[(lineups["season"] == x["Season"]) & ((lineups["home_player1_id"] == x["Player ID"]) | (lineups["home_player2_id"] == x["Player ID"]) | (lineups["home_player3_id"] == x["Player ID"]) | (lineups["home_player4_id"] == x["Player ID"]) | (lineups["home_player5_id"] == x["Player ID"]) |
                                (lineups["visitor_player1_id"] == x["Player ID"]) | (lineups["visitor_player2_id"] == x["Player ID"]) | (lineups["visitor_player3_id"] == x["Player ID"]) | (lineups["visitor_player4_id"] == x["Player ID"]) | (lineups["visitor_player5_id"] == x["Player ID"]))]["game_id"].count()), axis=1)

player_info.to_csv("player_info.csv", index=True)

In [4]:
# for testing
id = 2544

lineups[(lineups["season"] == "2011-12") & ((lineups["home_player1_id"] == id) | (lineups["home_player2_id"] == id) | (lineups["home_player3_id"] == id) | (lineups["home_player4_id"] == id) | (lineups["home_player5_id"] == id) |
        (lineups["visitor_player1_id"] == id) | (lineups["visitor_player2_id"] == id) | (lineups["visitor_player3_id"] == id) | (lineups["visitor_player4_id"] == id) | (lineups["visitor_player5_id"] == id))]["game_id"].count()

51

In [ ]:
player_info[player_info["Player"] == "LeBron James"]

In [33]:
# for testing

def extract_season(data):
    if int(data[1:3]) < 9:
        return("20{}-0{}".format(data[1:3], int(data[1:3]) + 1))
    else:
        return("20{}-{}".format(data[1:3], int(data[1:3]) + 1))


lineups["season"] = lineups["game_id"].astype(str).apply(extract_season)