In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import sys
sys.path.insert(0, '../../src/')
import data_loader
pd.set_option('display.max_columns', None)

In [5]:
players = pd.read_csv("playerlist.csv")

In [6]:
players.head(10)

,Unnamed: 0,DISPLAY_FIRST_LAST,DISPLAY_LAST_COMMA_FIRST,FROM_YEAR,GAMES_PLAYED_FLAG,OTHERLEAGUE_EXPERIENCE_CH,PERSON_ID,PLAYERCODE,ROSTERSTATUS,TEAM_ABBREVIATION,TEAM_CITY,TEAM_CODE,TEAM_ID,TEAM_NAME,TO_YEAR
0,0,Alaa Abdelnaby,"Abdelnaby, Alaa",1990,Y,0,76001,HISTADD_alaa_abdelnaby,0,NaN,NaN,NaN,0,NaN,1994
1,1,Zaid Abdul-Aziz,"Abdul-Aziz, Zaid",1968,Y,0,76002,HISTADD_zaid_abdul-aziz,0,NaN,NaN,NaN,0,NaN,1977
2,2,Kareem Abdul-Jabbar,"Abdul-Jabbar, Kareem",1969,Y,0,76003,HISTADD_kareem_abdul-jabbar,0,NaN,NaN,NaN,0,NaN,1988
3,3,Mahmoud Abdul-Rauf,"Abdul-Rauf, Mahmoud",1990,Y,0,51,mahmoud_abdul-rauf,0,NaN,NaN,NaN,0,NaN,2000
4,4,Tariq Abdul-Wahad,"Abdul-Wahad, Tariq",1997,Y,0,1505,tariq_abdul-wahad,0,NaN,NaN,NaN,0,NaN,2003
5,5,Shareef Abdur-Rahim,"Abdur-Rahim, Shareef",1996,Y,0,949,shareef_abdur-rahim,0,NaN,NaN,NaN,0,NaN,2007
6,6,Tom Abernethy,"Abernethy, Tom",1976,Y,0,76005,HISTADD_tom_abernethy,0,NaN,NaN,NaN,0,NaN,1980
7,7,Forest Able,"Able, Forest",1956,Y,0,76006,HISTADD_frosty_able,0,NaN,NaN,NaN,0,NaN,1956
8,8,John Abramovic,"Abramovic, John",1946,Y,0,76007,HISTADD_brooms_abramovic,0,NaN,NaN,NaN,0,NaN,1947
9,9,Alex Abrines,"Abrines, Alex",2016,Y,0,203518,alex_abrines,0,NaN,NaN,NaN,0,NaN,2018

In [3]:
season_2018 = data_loader.load_data(seasons=["2018-19"])

In [4]:
seasons_ldg = data_loader.load_game_data(seasons=["2018-19"])

Loaded PBP-data

In [93]:
seasons_ldg.loc[21800794]

play_count                                449
season_name                           2018-19
visitor_team_id                  1610612745.0
visitor_team_city                     Houston
visitor_team_nickname                 Rockets
visitor_final_score                       118
home_final_score                          110
home_win                                False
home_team_id                     1610612756.0
home_team_city                        Phoenix
home_team_nickname                       Suns
periods                                     4
minutes_played                           48.0
visitor_players_deployed                    8
home_players_deployed                       8
visitor_fg_made                            43
visitor_fg_missed                          44
visitor_3PT_made                           13
visitor_3PT_missed                         28
home_fg_made                               45
home_fg_missed                             39
home_3PT_made                               7
home_3PT_missed                            18
visitor_ft_made                            19
visitor_ft_missed                           6
home_ft_made                               13
home_ft_missed                              5
visitor_rebound                            43
home_rebound                               38
visitor_team_rebound                        4
home_team_rebound                           5
visitor_turnover                           12
home_turnover                              17
visitor_team_turnover                       2
home_team_turnover                          0
visitor_foul                               19
home_foul                                  20
visitor_subs                               24
home_subs                                  20
visitor_timeout                             5
home_timeout                                7
visitor_jump_balls_won                      0
home_jump_balls_won                         2
tip_off_winner                    HOME_PLAYER
visitor_ejection                            0
home_ejection                               0
visitor_team_ejection                       0
home_team_ejection                          0
home_scoring_leader                   1628367
home_scoring_leader_points               25.0
visitor_scoring_leader                 201935
visitor_scoring_leader_points            44.0
Name: 21800794, dtype: object

In [43]:
season_2018

,Unnamed: 0,EVENTMSGACTIONTYPE,EVENTMSGTYPE,EVENTNUM,GAME_ID,HOMEDESCRIPTION,PCTIMESTRING,PERIOD,PERSON1TYPE,PERSON2TYPE,PERSON3TYPE,PLAYER1_ID,PLAYER1_NAME,PLAYER1_TEAM_ABBREVIATION,PLAYER1_TEAM_CITY,PLAYER1_TEAM_ID,PLAYER1_TEAM_NICKNAME,PLAYER2_ID,PLAYER2_NAME,PLAYER2_TEAM_ABBREVIATION,PLAYER2_TEAM_CITY,PLAYER2_TEAM_ID,PLAYER2_TEAM_NICKNAME,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ABBREVIATION,PLAYER3_TEAM_CITY,PLAYER3_TEAM_ID,PLAYER3_TEAM_NICKNAME,SCORE,SCOREMARGIN,VISITORDESCRIPTION,WCTIMESTRING,season_name
0,0,0,PERIOD_BEGIN,2,21800794,NaN,12:00,1,0.0,0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9:11 PM,2018-19
1,1,0,JUMP_BALL,4,21800794,Jump Ball Ayton vs. Faried: Tip to Okobo,12:00,1,HOME_PLAYER,VISITOR_PLAYER,HOME_PLAYER,1629028,Deandre Ayton,PHX,Phoenix,1610612756.0,Suns,202702,Kenneth Faried,HOU,Houston,1610612745.0,Rockets,1629059,Elie Okobo,PHX,Phoenix,1610612756.0,Suns,NaN,NaN,NaN,9:11 PM,2018-19
2,2,1,TURNOVER,7,21800794,Jackson Bad Pass Turnover (P1.T1),11:39,1,HOME_PLAYER,VISITOR_PLAYER,0,1628367,Josh Jackson,PHX,Phoenix,1610612756.0,Suns,201935,James Harden,HOU,Houston,1610612745.0,Rockets,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Harden STEAL (1 STL),9:11 PM,2018-19
3,3,Driving Layup,FIELD_GOAL_MADE,9,21800794,NaN,11:31,1,VISITOR_PLAYER,0,0,201935,James Harden,HOU,Houston,1610612745.0,Rockets,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,2 - 0,-2,Harden 3' Driving Layup (2 PTS),9:12 PM,2018-19
4,4,2,FOUL,10,21800794,Bridges S.FOUL (P1.T1) (E.Dalen),11:31,1,HOME_PLAYER,VISITOR_PLAYER,TIMEOUT,1628969,Mikal Bridges,PHX,Phoenix,1610612756.0,Suns,201935,James Harden,HOU,Houston,1610612745.0,Rockets,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9:12 PM,2018-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
582463,431,1,TIMEOUT,634,21801037,NaN,0:04,4,VISITOR_TEAM,0,0,1610612739,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cavaliers Timeout: Regular (Reg.6 Short 0),10:49 PM,2018-19
582464,432,0,SUBSTITUTION,635,21801037,NaN,0:04,4,VISITOR_PLAYER,VISITOR_PLAYER,0,1627790,Ante Zizic,CLE,Cleveland,1610612739.0,Cavaliers,203903,Jordan Clarkson,CLE,Cleveland,1610612739.0,Cavaliers,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SUB: Clarkson FOR Zizic,10:50 PM,2018-19
582465,433,Fadeaway Jumper,FIELD_GOAL_MISSED,638,21801037,NaN,0:02,4,VISITOR_PLAYER,0,0,203917,Nik Stauskas,CLE,Cleveland,1610612739.0,Cavaliers,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MISS Stauskas 24' 3PT Fadeaway Jumper,10:51 PM,2018-19
582466,434,live,REBOUND,639,21801037,Kleber REBOUND (Off:5 Def:7),0:02,4,HOME_PLAYER,0,0,1628467,Maxi Kleber,DAL,Dallas,1610612742.0,Mavericks,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10:51 PM,2018-19
582467,435,0,PERIOD_END,640,21801037,NaN,0:00,4,0.0,0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,116 - 121,5,NaN,10:51 PM,2018-19

In [163]:
# Number of Phoenix Suns players that were substituted in the first period
season_2018[(season_2018["EVENTMSGTYPE"] == "SUBSTITUTION") & (season_2018["PERIOD"] == 1) & (season_2018["PLAYER1_TEAM_ID"] == "1610612756.0")].groupby("GAME_ID")["PLAYER1_NAME"].nunique()

GAME_ID
21800013    5
21800033    5
21800047    5
21800060    7
21800080    2
           ..
21801160    6
21801174    5
21801189    3
21801200    4
21801216    5
Name: PLAYER1_NAME, Length: 82, dtype: int64

In [162]:
# Phoenix Suns players that were substituted in the first period
season_2018[(season_2018["EVENTMSGTYPE"] == "SUBSTITUTION") & (season_2018["PERIOD"] == 1) & (season_2018["PLAYER1_TEAM_ID"] == "1610612756.0")].groupby("GAME_ID")["PLAYER1_NAME"].unique()

GAME_ID
21800013    [Ryan Anderson, Devin Booker, Deandre Ayton, I...
21800033    [Ryan Anderson, Deandre Ayton, Isaiah Canaan, ...
21800047    [Deandre Ayton, Ryan Anderson, Devin Booker, I...
21800060    [Ryan Anderson, Devin Booker, Deandre Ayton, I...
21800080                       [Ryan Anderson, Isaiah Canaan]
                                  ...
21801160    [Dragan Bender, Richaun Holmes, Mikal Bridges,...
21801174    [Dragan Bender, Mikal Bridges, Devin Booker, R...
21801189            [Ray Spalding, Mikal Bridges, Elie Okobo]
21801200    [Ray Spalding, Mikal Bridges, Elie Okobo, Josh...
21801216    [Ray Spalding, Mikal Bridges, Elie Okobo, Josh...
Name: PLAYER1_NAME, Length: 82, dtype: object

In [161]:
# Phoenix Suns players that were substituted in the whole match
season_2018[(season_2018["EVENTMSGTYPE"] == "SUBSTITUTION") & (season_2018["PLAYER1_TEAM_ID"] == "1610612756.0")].groupby("GAME_ID")["PLAYER1_NAME"].unique()

GAME_ID
21800013    [Ryan Anderson, Devin Booker, Deandre Ayton, I...
21800033    [Ryan Anderson, Deandre Ayton, Isaiah Canaan, ...
21800047    [Deandre Ayton, Ryan Anderson, Devin Booker, I...
21800060    [Ryan Anderson, Devin Booker, Deandre Ayton, I...
21800080    [Ryan Anderson, Isaiah Canaan, Trevor Ariza, E...
                                  ...
21801160    [Dragan Bender, Richaun Holmes, Mikal Bridges,...
21801174    [Dragan Bender, Mikal Bridges, Devin Booker, R...
21801189    [Ray Spalding, Mikal Bridges, Elie Okobo, Troy...
21801200    [Ray Spalding, Mikal Bridges, Elie Okobo, Josh...
21801216    [Ray Spalding, Mikal Bridges, Elie Okobo, Josh...
Name: PLAYER1_NAME, Length: 82, dtype: object

In [125]:
GAME_ID_STR = "GAME_ID"
pbp_grouped = season_2018.groupby(GAME_ID_STR)

In [128]:
game_data = pbp_grouped.size().to_frame(name="play_count")

In [152]:
game_data["home_team_id"] = pbp_grouped.apply(lambda x: x[x["PERSON1TYPE"] == 'HOME_PLAYER']["PLAYER1_TEAM_ID"].iloc[0])
game_data["visitor_team_id"] = pbp_grouped.apply(lambda x: x[x["PERSON1TYPE"] == 'VISITOR_PLAYER']["PLAYER1_TEAM_ID"].iloc[0])

In [155]:
game_data["home"]

          play_count  home_team_id visitor_team_id
GAME_ID
21800001         492  1610612738.0    1610612755.0
21800002         522  1610612744.0    1610612760.0
21800003         487  1610612766.0    1610612749.0
21800004         478  1610612765.0    1610612751.0
21800005         453  1610612754.0    1610612763.0
...              ...           ...             ...
21801226         474  1610612749.0    1610612760.0
21801227         443  1610612759.0    1610612742.0
21801228         434  1610612743.0    1610612750.0
21801229         555  1610612746.0    1610612762.0
21801230         422  1610612757.0    1610612758.0

[1230 rows x 3 columns]