# Feature selection and intial predictions

In [1]:
%reload_ext autoreload
%autoreload 2
import os 
import sys
import pandas as pd
import numpy as np
from datetime import datetime
import plotly 
import plotly.graph_objects as go
from datetime import timedelta

sys.path.insert(0, "./../../")

# from src.preprocessing.feature_preparation import prepare_features_for_season_based_predictions
from src.preprocessing.DataPreparator import DataPreparator

In [6]:
%%time
data_p = DataPreparator(force_recompute_method_data=False, force_recompute_class_data=False)
all_games = data_p.get_games_df()
display(all_games)

Loading game data from file ...

,GAME_ID,play_count,home_team_id,visitor_team_id,home_record_wins,home_record_losses,season_name,visitor_team_city,visitor_team_nickname,home_final_score,...,visitor_recent_fg_made,visitor_recent_fg_missed,visitor_recent_3PT_made,visitor_recent_3PT_missed,visitor_recent_ft_made,visitor_recent_ft_missed,visitor_recent_players_deployed,visitor_recent_rebound,visitor_recent_turnover,visitor_recent_foul
0,20000001,429,1610612752,1610612755,0,1,2000-2001,Philadelphia,76ers,72,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20000002,510,1610612751,1610612739,0,1,2000-2001,Cleveland,Cavaliers,82,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20000003,478,1610612753,1610612764,1,0,2000-2001,Washington,Wizards,97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20000004,448,1610612737,1610612766,0,1,2000-2001,Charlotte,Hornets,82,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20000005,505,1610612761,1610612765,0,1,2000-2001,Detroit,Pistons,95,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22960,21801226,474,1610612749,1610612760,60,22,2018-2019,Oklahoma City,Thunder,116,...,42.8,53.3,13.2,24.4,14.6,6.2,10.3,46.7,12.0,21.1
22961,21801227,443,1610612759,1610612742,48,34,2018-2019,Dallas,Mavericks,105,...,40.8,49.9,14.4,28.0,18.3,6.2,11.0,49.2,10.8,21.3
22962,21801228,434,1610612743,1610612750,54,28,2018-2019,Minnesota,Timberwolves,99,...,42.0,47.8,10.8,18.2,19.0,5.5,10.3,42.1,12.7,20.3
22963,21801229,555,1610612746,1610612762,48,34,2018-2019,Utah,Jazz,143,...,43.1,41.7,12.4,19.4,18.5,6.4,11.3,46.9,14.8,21.7
22964,21801230,422,1610612757,1610612758,53,29,2018-2019,Sacramento,Kings,136,...,42.8,51.8,11.9,17.4,15.6,5.2,10.4,45.4,10.5,18.2

CPU times: total: 453 ms
Wall time: 455 ms

In [27]:
# display(all_games["home_common_lineup"])
x_train, y_train, x_test, y_test, used_cols = data_p.prepare_data_splits("2017-2018")
# prepared_df = data_p.prepare_static_data()
display(prepared_df)

Columns that will be used are of lengths:
    - x_home_cols: 16,
    - x_visit_cols length: 16

,winner_team_id,winner_recent_TSP,winner_final_score_diff,winner_recent_home_game_ratio,winner_recent_win_ratio,winner_recent_points,winner_recent_fg_made,winner_recent_fg_missed,winner_recent_3PT_made,winner_recent_3PT_missed,...,loser_recent_fg_missed,loser_recent_3PT_made,loser_recent_3PT_missed,loser_recent_ft_made,loser_recent_ft_missed,loser_recent_players_deployed,loser_recent_rebound,loser_recent_turnover,loser_recent_foul,loser_common_lineup
0,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22960,23,0.504700,1.7,0.7,0.6,113.4,42.8,53.3,13.2,24.4,...,48.5,14.0,23.6,19.8,5.5,10.0,52.0,12.3,19.8,0
22961,22,0.543685,1.5,0.4,0.5,110.6,42.9,46.8,10.2,18.3,...,49.9,14.4,28.0,18.3,6.2,11.0,49.2,10.8,21.3,0
22962,6,0.501975,-4.9,0.4,0.4,102.3,39.3,49.9,9.0,20.7,...,47.8,10.8,18.2,19.0,5.5,10.3,42.1,12.7,20.3,0
22963,9,0.594640,-0.3,0.5,0.6,115.8,41.6,43.0,11.4,18.0,...,41.7,12.4,19.4,18.5,6.4,11.3,46.9,14.8,21.7,0
22964,20,0.550658,7.8,0.4,0.8,116.8,44.0,49.1,10.4,20.7,...,51.8,11.9,17.4,15.6,5.2,10.4,45.4,10.5,18.2,0

['home_team_id',
 'home_recent_TSP',
 'home_final_score_diff',
 'home_recent_home_game_ratio',
 'home_recent_win_ratio',
 'home_recent_points',
 'home_recent_fg_made',
 'home_recent_fg_missed',
 'home_recent_3PT_made',
 'home_recent_3PT_missed',
 'home_recent_ft_made',
 'home_recent_ft_missed',
 'home_recent_players_deployed',
 'home_recent_rebound',
 'home_recent_turnover',
 'home_recent_foul',
 'visitor_team_id',
 'visitor_recent_TSP',
 'visitor_final_score_diff',
 'visitor_recent_home_game_ratio',
 'visitor_recent_win_ratio',
 'visitor_recent_points',
 'visitor_recent_fg_made',
 'visitor_recent_fg_missed',
 'visitor_recent_3PT_made',
 'visitor_recent_3PT_missed',
 'visitor_recent_ft_made',
 'visitor_recent_ft_missed',
 'visitor_recent_players_deployed',
 'visitor_recent_rebound',
 'visitor_recent_turnover',
 'visitor_recent_foul']

In [29]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import RFE
from operator import itemgetter

regressor = RandomForestRegressor(n_estimators=100, max_depth=10)
#===========================================================================
# perform a scikit-learn Recursive Feature Elimination (RFE)
#===========================================================================
rfe = RFE(regressor, n_features_to_select=10)
rfe.fit(x_train, y_train)

features = [(i, used_cols[i]) for i in range(len(x_train[0]))]
for x, y in (sorted(zip(rfe.ranking_ , features), key=itemgetter(0))):
    print(x, y)

1 (1, 'home_recent_TSP')
1 (2, 'home_final_score_diff')
1 (5, 'home_recent_points')
1 (11, 'home_recent_ft_missed')
1 (18, 'visitor_final_score_diff')
1 (21, 'visitor_recent_points')
1 (25, 'visitor_recent_3PT_missed')
1 (27, 'visitor_recent_ft_missed')
1 (29, 'visitor_recent_rebound')
1 (31, 'visitor_recent_foul')
2 (9, 'home_recent_3PT_missed')
3 (15, 'home_recent_foul')
4 (30, 'visitor_recent_turnover')
5 (7, 'home_recent_fg_missed')
6 (26, 'visitor_recent_ft_made')
7 (13, 'home_recent_rebound')
8 (17, 'visitor_recent_TSP')
9 (24, 'visitor_recent_3PT_made')
10 (0, 'home_team_id')
11 (6, 'home_recent_fg_made')
12 (10, 'home_recent_ft_made')
13 (23, 'visitor_recent_fg_missed')
14 (22, 'visitor_recent_fg_made')
15 (28, 'visitor_recent_players_deployed')
16 (14, 'home_recent_turnover')
17 (8, 'home_recent_3PT_made')
18 (16, 'visitor_team_id')
19 (12, 'home_recent_players_deployed')
20 (4, 'home_recent_win_ratio')
21 (3, 'home_recent_home_game_ratio')
22 (19, 'visitor_recent_home_game_ratio')
23 (20, 'visitor_recent_win_ratio')

In [ ]:
# x_train, y_train, x_test, y_test = data_p.prepare_data_splits("2017-2018")
# x_train[:2]
display(all_games.columns)

## Feature selection
In this notebook the following steps will be performed:
1. Influence of each feature on the "home_win" target will be performed
2. Correlations between features that find the same information will plotted and afterwards the given features will be eliminated.
3. N-features will be put together and the optimal features which yield the highest accuracy will be found.

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score

# max_depth=100
r_forest = RandomForestRegressor(n_estimators=150, criterion='squared_error', 
                                 random_state=42, max_depth=13)
r_forest.fit(x_train, y_train)

# evaluate on train data set ->> overfitting but just to see the accuracy
print("Starting predictions ...")
y_pred_train = []
for row in x_train:
    y_pred_train.append(round(r_forest.predict([row])[0]))
    
print(f"Accuracy on the train set is: {accuracy_score(y_train, y_pred_train, normalize=True) * 100} %")

In [ ]:
print("Evaluating on the test data set!")

y_pred_test = []
for row in x_test:
    y_pred_test.append(round(r_forest.predict([row])[0]))
    
print(f"Accuracy on the train set is: {accuracy_score(y_test, y_pred_test, normalize=True) * 100} %")